# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    container: rust:slim-bookworm
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install build script dependencies
        run: apt update && apt install -y git python3 xz-utils zip
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install Emscripten
        uses: emscripten-core/setup-emsdk@v15
      - name: Verify Emscripten
        run: emcc -v
      - name: Build dist
        run: ./emscripten/build.sh dist
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
